theme: jekyll-theme-primer
title: Regional Business Development & Partnerships Portfolio
description: Regional Business Development & Partnerships Professional | Forex, Fintech & SaaS | APAC Growth | Strategic Partnerships | Key Account Management
